import json
import os

try:
    from bs4 import BeautifulSoup
    from src.utils.country_html_cache import get_country_html
except ImportError:
    import sys

    src_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    if src_root not in sys.path:
        sys.path.insert(0, src_root)
    from bs4 import BeautifulSoup
    from utils.country_html_cache import get_country_html


def _get_project_root():
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def _load_countries(countries_path: str) -> dict:
    with open(countries_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _parse_country_people(html: str) -> list[dict]:
    soup = BeautifulSoup(html, "html.parser")

    people: list[dict] = []
    for table in soup.select("table.table_noborder"):
        heading = table.find("b")
        if heading and heading.get_text(strip=True).lower() == "people":
            for a in table.find_all("a", href=True):
                person_name = a.get_text(strip=True)
                person_link = a.get("href")
                if person_name and person_link:
                    people.append({"name": person_name, "link": person_link})
            break

    # Deduplicate by link (keep first name)
    unique: list[dict] = []
    seen = set()
    for item in people:
        key = item.get("link")
        if key and key not in seen:
            seen.add(key)
            unique.append(item)

    return unique


def _fetch_country_people(country_link: str) -> list[dict]:
    html = get_country_html(country_link, fetch_if_missing=True)
    return _parse_country_people(html)


def extract_persons():
    """
    Extract person link list per country from countries.json.

    Requires:
        data/countries.json (generated by extract_countries)

    Output:
        data/persons.json
    """
    project_root = _get_project_root()
    countries_path = os.path.join(project_root, "data", "raw", "countries.json")
    persons_path = os.path.join(project_root, "data", "raw", "persons.json")
    os.makedirs(os.path.dirname(persons_path), exist_ok=True)

    if not os.path.exists(countries_path):
        raise FileNotFoundError(
            f"Missing {countries_path}. Run countries pipeline first to generate it."
        )

    country_sections = _load_countries(countries_path)

    data: dict[str, list[dict]] = {}
    seen = set()

    for alliance, countries in country_sections.items():
        print(f"Processing alliance: {alliance}")
        data.setdefault(alliance, [])

        for country in countries:
            country_name = country.get("name")
            country_link = country.get("link")
            if not country_link:
                continue

            try:
                people = _fetch_country_people(country_link)
            except Exception as e:
                print(f"  Error parsing people for {country_name}: {e}")
                continue

            for person in people:
                person_link = person.get("link")
                if not person_link:
                    continue

                key = (alliance, country_name, person_link)
                if key in seen:
                    continue
                seen.add(key)

                data[alliance].append(
                    {
                        "country_name": country_name,
                        "country_link": country_link,
                        "alliance": alliance,
                        "person_name": person.get("name"),
                        "person_link": person_link,
                    }
                )

    with open(persons_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)

    return data


if __name__ == "__main__":
    data = extract_persons()
    print("Data saved to data/raw/persons.json")
    first_alliance = next(iter(data.keys()), None)
    preview = data.get(first_alliance, [])[:5] if first_alliance else []
    print(json.dumps(preview, indent=2, ensure_ascii=False))
